[ids]

*
-0fac:1ade
046d:4074

[main]

mouse1 = overload(side1, mouse1)
mouse2 = overload(side2, mouse2)

[meta]
tab = layer(meta)

[side1]
rightmouse = C-c
leftmouse = C-v
middlemouse = enter
leftmeta = backspace
scrolldown = swap(scrolling)
scrollup = swap(scrolling)

[scrolling:A]
scrolldown = A-tab
scrollup = A-S-tab

[side2]
rightmouse = C-x
leftmouse = C-z
scrolldown = swap(scrolling2)
scrollup = swap(scrolling2)

[scrolling2:S]
scrolldown = S-scrolldown
scrollup = S-scrollup





